name: Build Windows EXE

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        fi

    - name: Clean previous builds
      shell: bash
      run: |
        rm -rf build dist

    - name: Build EXE
      shell: bash
      run: |
        # Optional: add --icon=icon.ico if you have an icon file in your repo
        pyinstaller --onefile app.py

    - name: List build folder
      shell: bash
      run: ls -la dist

    - name: Upload EXE as artifact
      uses: actions/upload-artifact@v4
      with:
        name: Sainik-EXE
        path: dist/app.exe

        
